### ISSUE TITLE
Install: 'openssl/err.h' file not found

### ISSUE THREAD

**Issue by Javdat** [s-u/PKI#17]
Hi,

I am trying to install PKI in R 3.3.1 under OS X El Capitan .

Unfortunately install is stoping with an error:

`
In file included from init.c:1:
./pki.h:11:10: fatal error: 'openssl/err.h' file not found
# include <openssl/err.h>

```
     ^
```

1 error generated.
make: **\* [init.o] Error 1
ERROR: compilation failed for package ‘PKI’
`

Even though openssl is installed through homebrew.

**Comment by jeroenooms** [comment]
Try `brew link --force openssl`. Also have a look at the openssl R package.

**Comment by Javdat** [comment]
```
Warning: Refusing to link: openssl
Linking keg-only openssl means you may end up linking against the insecure,
deprecated system OpenSSL while using the headers from Homebrew's openssl.
Instead, pass the full include/library paths to your compiler e.g.:
  -I/usr/local/opt/openssl/include -L/usr/local/opt/openssl/lib
```

Homebrew started refusing linking openssl

**Comment by jeroenooms** [comment]
Ow that sucks. I don't think `PKI` currently has a configure script to pass those flags. What do you need PKI for?

**Comment by Javdat** [comment]
I need 'rsconnect' to publish shiny apps. 'rsconnect' requires 'PKI'

**Comment by jeroenooms** [comment]
Why don't you install the `PKI` binary package for mac?

**Comment by Javdat** [comment]
The binary package did install. Thank you :)

Still, for the future the issue needs to be addressed, I think.

**Comment by jeroenooms** [comment]
Yes I will try to persuade rstudio to switch to the openssl pkg.

**Comment by s-u** [comment]
More recent XCode strips openssl headers, but the libraries are there so if you want to compile from sources, you only need to add the headers from the Apple open source site.

**Comment by MatthewWDemas** [comment]
I also had an issue installing PKI under MacOS Sierra running R 3.3.2-MRO. Running: 
`install.packages('PKI',,'http://www.rforge.net/')`
from http://www.rforge.net/PKI/files/ in the R console worked for me.

**Comment by s-u** [comment]
You're missing headers for OpenSSL. Please try the latest version - it will  download headers from Apple if you failed to install them yourself (requires an Internet connection).

**Comment by FlorianScharf** [comment]
Hey there, 

at first, I observed the error above. So I tried to install using the command above which ends in a new error message: `checking for library containing RSA_generate_key_ex... no
configure: error: Cannot find usable crypto library
ERROR: configuration failed for package ‘PKI’`
(I'm on Mac OS Sierra.)
Can you give me any hints on what kind of crypto library to look for/install?

**Comment by nitky** [comment]
I solved this issue based on the [page](https://support.rstudio.com/hc/en-us/community/posts/115005670527-Install-PKI-on-Mac-homebrew-install-of-R-and-openssl). (Mac OS Sierra)

```sh
brew install openssl gettext
```

edit ~/.R/Makevars
```basemake
CFLAGS = -g -O3 -Wall -pedantic -mtune=native -I/usr/local/opt/openssl/include -I/usr/local/opt/gettext/include
CXXFLAGS = -g -O3 -Wall -pedantic -mtune=native -I/usr/local/opt/openssl/include -I/usr/local/opt/gettext/include
LDFLAGS = -L/usr/local/opt/openssl/lib -L/usr/local/opt/gettext/lib
```
Let's try!
```sh
install.packages('PKI')
```

**Comment by s-u** [comment]
Please don't use brew - it conflicts with system openssl. The recommended way to is add missing system headers from Apple or use the latest PKI version which fetches them automatically when missing.

**Comment by s-u** [comment]
Automatic fetch of Apple includes has been added in 9e2360

**Comment by cafletezbrant** [comment]
I am just adding that installing via `devtools::install_github()` worked for me, but attempting to use rforge` did not.

**Comment by russelldb** [comment]
Why is this closed? The issues still exists. I'm on macOs Sierra, attempting to install the latest PKI fails, it even claims to download the header files, and then still fails:

   ```
 configure: Missing OpenSSL headers on macOS,
configure: attempting to get headers from Apple...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 14.6M  100 14.6M    0     0  1199k      0  0:00:12  0:00:12 --:--:-- 2295k
checking openssl/ssl.h usability... yes
checking openssl/ssl.h presence... yes
checking for openssl/ssl.h... yes
checking openssl/rsa.h usability... yes
checking openssl/rsa.h presence... yes
checking for openssl/rsa.h... yes
checking for library containing RSA_generate_key_ex... no
configure: error: Cannot find usable crypto library
ERROR: configuration failed for package ‘PKI’
* removing ‘/usr/local/lib/R/3.5/site-library/PKI’

The downloaded source packages are in
	‘/private/var/folders/g6/bd1426g11kv53m30xgmg9v500000gn/T/Rtmpxft2TP/downloaded_packages’
Warning message:
In install.packages("PKI") :
  installation of package ‘PKI’ had non-zero exit status
```

**Comment by swvanderlaan** [comment]
At my side the same issue also persists (see below).

Is there a fix?

```
install.packages('PKI',,'http://www.rforge.net/')
Installing package into ‘/usr/local/lib/R/3.5/site-library’
(as ‘lib’ is unspecified)
trying URL 'http://www.rforge.net/src/contrib/PKI_0.1-5.tar.gz'
Content type 'application/x-gzip' length 68047 bytes (66 KB)
==================================================
downloaded 66 KB

* installing *source* package ‘PKI’ ...
checking for gcc... clang
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether clang accepts -g... yes
checking for clang option to accept ISO C89... none needed
checking how to run the C preprocessor... clang -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... rm: conftest.dSYM: is a directory
rm: conftest.dSYM: is a directory
yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking openssl/ssl.h usability... no
checking openssl/ssl.h presence... no
checking for openssl/ssl.h... no
configure: Missing OpenSSL headers on macOS,
configure: attempting to get headers from Apple...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 14.6M  100 14.6M    0     0  7292k      0  0:00:02  0:00:02 --:--:-- 7294k
checking openssl/ssl.h usability... yes
checking openssl/ssl.h presence... yes
checking for openssl/ssl.h... yes
checking openssl/rsa.h usability... yes
checking openssl/rsa.h presence... yes
checking for openssl/rsa.h... yes
checking for library containing RSA_generate_key_ex... no
configure: error: Cannot find usable crypto library
ERROR: configuration failed for package ‘PKI’
* removing ‘/usr/local/lib/R/3.5/site-library/PKI’
* restoring previous ‘/usr/local/lib/R/3.5/site-library/PKI’

The downloaded source packages are in
	‘/private/var/folders/7r/ns6f04xj55j72y97pvwtwxj0000_2q/T/RtmprodcPe/downloaded_packages’
Warning message:
In install.packages("PKI", , "http://www.rforge.net/") :
  installation of package ‘PKI’ had non-zero exit status
```

**Comment by jeroen** [comment]
@swvanderlaan the R package `openssl` does everything and much more than PKI and works on all platforms and is actively maintained.

**Comment by yenicelik** [comment]
Still seems to persist

**Comment by s-u** [comment]
@yenicelik It doesn't. This issue has been fixed long time ago - but requires internet connection since your system doesn't have the required headers so they need to be downloaded. If you see any other issue, please first check the latest version (it works just fine and it is available from CRAN which is the recommended way to get it unless you know what your'e doing) and if it still persists, file a new issue.

**Comment by swvanderlaan** [comment]
Yes, I had revisited this and also installed `openssl` via r. But that said: apparently other non-r programs need it as well and install it (when you use `homebrew`) and that's where things go awry. So somehow - and I am not an expert - this needs to be tackled at some point in the (near) future...

**Comment by s-u** [comment]
What need to be tackled? If you use Homebrew, then make sure you install *everything* from Homebrew including R as it is incompatible with native programs. If you use R form CRAN then it just works.

**Comment by swvanderlaan** [comment]
Yep. So this is exactly my workflow: I install `macOS` and than I install `homebrew` and `r` via `homebrew`. 

Still, if you install packages in r `openssl` might be needed and apparently things go awry there. Either `openssl` installed through `homebrew` is still not properly recognised by `r` or indeed those other packages do not work well in this scenario. 

I am just a user, that adheres to the workflow you describe @s-u , and I just install a package in `r` when I need it. I expect that it then works. And when it doesn't I look at the developer of any package that apparently is involved - dependency hell _does_ make that hard to determine. So in this case if it isn't `openssl` then _mea culpa_ and I have said nothing. :-) Of course it _is_ too easy to simply state that then it is solely on the other programs' end - there is an interaction. And both sides need to be aware in IMO. In any case, didn't want to be offensive, so apologies if I was.
